/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bai1;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pham Thu Trang
 */
public class bai1 extends javax.swing.JFrame {
    public bai1() {
        initComponents();
    }
    List<Student> list=new ArrayList<>();
    public void addStudent(){
        
       Student sv=new Student();
       sv.name=txthoten.getText();
       sv.marks=Double.parseDouble(txtdiem.getText());
       sv.major=(String) cboNganh.getSelectedItem();
       list.add(sv);
      
       txthocluc.setText(sv.getGrade());
       chkthuong.setSelected(sv.isBonus());
       
    }
    public void fillToTable(){
        DefaultTableModel model=(DefaultTableModel)tblStudent.getModel();
        model.setRowCount(0);
       
        for(Student svien:list){
      Object[] row=new Object[]{svien.name,svien.marks,svien.major,svien.getGrade(),svien.isBonus()};
        model.addRow(row);
    }}
    public void showDetail(){
     int index=tblStudent.getSelectedRow();
        Student sv=list.get(index);
        
       txthoten.setText((String) tblStudent.getValueAt(index,0));
       txtdiem.setText(tblStudent.getValueAt(index,1).toString());
       cboNganh.setSelectedItem((String) tblStudent.getValueAt(index, 2));
       txthocluc.setText((String)tblStudent.getValueAt(index, 3));
       chkthuong.setSelected((Boolean)tblStudent.getValueAt(index, 4));     
    }
    public void   removeStudent(){
        int index=tblStudent.getSelectedRow();
        list.remove(index);
        
    }
    public void  updateStudent(){
      int index=tblStudent.getSelectedRow();
        list.remove(index);
        
      Student sv=new Student();
       sv.name=txthoten.getText();
       sv.marks=Double.parseDouble(txtdiem.getText());
       sv.major=(String) cboNganh.getSelectedItem();
       txthocluc.setText(sv.getGrade());
       chkthuong.setSelected(sv.isBonus());
       list.add(sv);
       JOptionPane.showMessageDialog(this,"Cap nhat thanh cong");
    }
    public void  orderByName(){
        Comparator<Student> com=new Comparator<Student>() {

            @Override
            public int compare(Student o1, Student o2) {
                //To change body of generated methods, choose Tools | Templates.
            return o1.name.compareTo(o2.name);}
        };
      Collections.sort(list,com); // TODO add your handling code here:
    } 
    public void orderByMarks(){
        Comparator<Student> com=new  Comparator<Student>(){

            @Override
            public int compare(Student o1, Student o2) {
                Double d1=o1.marks; //To change body of generated methods, choose Tools | Templates.
                Double d2=o2.marks; 
            return d1.compareTo(d2);//To change body of generated methods, choose Tools | Templates.
            }
            
        };
       Collections.sort(list,com);        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnthem = new javax.swing.JButton();
        txthoten = new javax.swing.JTextField();
        txtdiem = new javax.swing.JTextField();
        cboNganh = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        txthocluc = new javax.swing.JTextField();
        btnxoa = new javax.swing.JButton();
        btnnhapmoi = new javax.swing.JButton();
        btncapnhat = new javax.swing.JButton();
        chkthuong = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudent = new javax.swing.JTable();
        btnXXtheoten = new javax.swing.JButton();
        btnXXtheodiem = new javax.swing.JButton();
        tbnthoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("QUẢN LÝ SINH VIÊN");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("HỌ VÀ TÊN ");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("ĐIẺM");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("NGÀNH");

        btnthem.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnthem.setForeground(new java.awt.Color(204, 0, 0));
        btnthem.setText("THÊM ");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        cboNganh.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "UDPM", "WEB", "DIG", "MAKET" }));
        cboNganh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboNganhActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("HỌC LỰC");

        txthocluc.setEditable(false);

        btnxoa.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnxoa.setForeground(new java.awt.Color(204, 0, 0));
        btnxoa.setText("XÓA");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        btnnhapmoi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnnhapmoi.setForeground(new java.awt.Color(204, 0, 0));
        btnnhapmoi.setText("NHẬP MỚI");
        btnnhapmoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnhapmoiActionPerformed(evt);
            }
        });

        btncapnhat.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btncapnhat.setForeground(new java.awt.Color(204, 0, 0));
        btncapnhat.setText("CẬP NHẬT");
        btncapnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncapnhatActionPerformed(evt);
            }
        });

        chkthuong.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        chkthuong.setText("Có phần thưởng ?");
        chkthuong.setEnabled(false);
        chkthuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkthuongActionPerformed(evt);
            }
        });

        tblStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "HỌ VÀ TÊN ", "ĐIỂM", "NGÀNH", "HỌC LỰC", "THƯỞNG"
            }
        ));
        tblStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStudentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblStudent);

        btnXXtheoten.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnXXtheoten.setText("XẮP XẾP THEO TÊN");
        btnXXtheoten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXXtheotenActionPerformed(evt);
            }
        });

        btnXXtheodiem.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnXXtheodiem.setText("XẮP XẾP THEO ĐIỂM");
        btnXXtheodiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXXtheodiemActionPerformed(evt);
            }
        });

        tbnthoat.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tbnthoat.setText("THOÁT");
        tbnthoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnthoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 982, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(83, 83, 83)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txthoten, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                                            .addComponent(txtdiem)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(chkthuong)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(cboNganh, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txthocluc, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jLabel1)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(btnXXtheoten)
                                .addGap(122, 122, 122)
                                .addComponent(btnXXtheodiem)
                                .addGap(74, 74, 74)
                                .addComponent(tbnthoat))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(btnthem)
                        .addGap(39, 39, 39)
                        .addComponent(btnxoa)
                        .addGap(63, 63, 63)
                        .addComponent(btncapnhat)
                        .addGap(72, 72, 72)
                        .addComponent(btnnhapmoi)))
                .addContainerGap(530, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txthoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtdiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cboNganh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txthocluc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(chkthuong)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnthem)
                    .addComponent(btnxoa)
                    .addComponent(btncapnhat)
                    .addComponent(btnnhapmoi))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXXtheoten)
                    .addComponent(btnXXtheodiem)
                    .addComponent(tbnthoat))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkthuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkthuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkthuongActionPerformed

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
this.addStudent();
this.fillToTable();// TODO add your handling code here:
    }//GEN-LAST:event_btnthemActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
this.removeStudent(); 
this.fillToTable();// TODO add your handling code here:
    }//GEN-LAST:event_btnxoaActionPerformed

    private void btncapnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncapnhatActionPerformed
this.updateStudent();
this.fillToTable();// TODO add your handling code here:
    }//GEN-LAST:event_btncapnhatActionPerformed

    private void btnnhapmoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnhapmoiActionPerformed
        // TODO add your handling code here:
        txthoten.setText(" ");
        txtdiem.setText(" ");
        txthocluc.setText(" ");
        
    }//GEN-LAST:event_btnnhapmoiActionPerformed

    private void cboNganhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboNganhActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_cboNganhActionPerformed

    private void btnXXtheotenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXXtheotenActionPerformed
this.orderByName();
this.fillToTable();// TODO add your handling code here:
    }//GEN-LAST:event_btnXXtheotenActionPerformed

    private void btnXXtheodiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXXtheodiemActionPerformed
     this.orderByMarks();
this.fillToTable();   // TODO add your handling code here:
    }//GEN-LAST:event_btnXXtheodiemActionPerformed

    private void tblStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStudentMouseClicked
        this.showDetail();
    }//GEN-LAST:event_tblStudentMouseClicked

    private void tbnthoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnthoatActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_tbnthoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bai1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnXXtheodiem;
    private javax.swing.JButton btnXXtheoten;
    private javax.swing.JButton btncapnhat;
    private javax.swing.JButton btnnhapmoi;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btnxoa;
    private javax.swing.JComboBox cboNganh;
    private javax.swing.JCheckBox chkthuong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblStudent;
    private javax.swing.JButton tbnthoat;
    private javax.swing.JTextField txtdiem;
    private javax.swing.JTextField txthocluc;
    private javax.swing.JTextField txthoten;
    // End of variables declaration//GEN-END:variables
}
